name: Playwright Test

on:
  push:
    branches:
      - main
      - "v*.*"
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-24.04

    env:
      ELIXIR_VERSION: "1.19.5"
      OTP_VERSION: "28.5"
      MIX_ENV: "e2e"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: "./e2e/package-lock.json"

      - name: Install Node dependencies
        working-directory: ./e2e
        run: npm ci

      - name: Check prettier
        working-directory: ./e2e
        run: npx prettier . --check

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.OTP_VERSION }}

      - name: Cache Mix dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}-

      - name: Install Mix dependencies
        run: mix deps.get

      - name: Compile project
        run: mix compile --warnings-as-errors

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('e2e/package-lock.json') }}

      - name: Install Playwright browsers
        working-directory: ./e2e
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install

      - name: Install Playwright OS dependencies
        working-directory: ./e2e
        run: npx playwright install-deps

      - name: Setup and build assets
        run: mix assets.setup && mix assets.build

      - name: Run e2e tests
        run: mix e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 1
