name: "Build Desktop App"

on:
  push:
    branches:
      - "v*.*.*"
      - "17-add-release-ci" # For testing only TODO: remove before merging

permissions:
  contents: read

jobs:
  app:
    name: "Desktop (${{ matrix.gui_target }})"
    env: 
      ELIXIR_VERSION: "1.20"
      OTP_VERSION: "29"
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-15
            gui_target: "aarch64-apple-darwin"
          - platform: macos-15-intel
            gui_target: "x86_64-apple-darwin"
          # - platform: windows-2022
          #   gui_target: "x86_64-pc-windows-msvc"
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.gui_target }}

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: rel/app/src-tauri
          cache-directories: |
            ~/.cargo/bin
          key: ${{ matrix.gui_target }}

      - name: Mix deps cache
        uses: actions/cache@v5
        with:
          path: |
            deps
          key: ${{ runner.os }}-mix-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}-${{ hashFiles('mix.lock') }}

      - name: Install Tauri CLI
        shell: bash
        run: |
          if ! command -v cargo-tauri &> /dev/null; then
            cargo install tauri-cli --version "=2.8.0" --locked
          else
            echo "cargo-tauri already installed: $(cargo-tauri --version)"
          fi

      - name: Install Mix dependencies
        shell: bash
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Create release
        shell: bash
        run: mix tauri.release

      # - name: Install trusted-signing-cli (Windows)
      #   if: runner.os == 'Windows'
      #   run: |
      #     cargo install trusted-signing-cli@0.9.0

      - name: Import Apple Developer Certificate
        # Prevents keychain from locking automatically for 3600 seconds.
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        if: runner.os == 'macOS'
        run: |
          echo $APPLE_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain
          security import certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
          security find-identity -v -p codesigning build.keychain

      - name: verify certificate
        if: runner.os == 'macOS'
        run: |
          CERT_INFO=$(security find-identity -v -p codesigning build.keychain | grep "Apple Development")
          CERT_ID=$(echo "$CERT_INFO" | awk -F'"' '{print $2}')
          echo "CERT_ID=$CERT_ID" >> $GITHUB_ENV
          echo "Certificate imported."

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MIX_ENV: prod
          # macOS codesigning/notarization
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          # APPLE_SIGNING_IDENTITY: "-" # ad-hoc signature
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          # Windows codesigning
          # AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          # AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          # AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          # AZURE_TRUSTED_SIGNING_ACCOUNT_NAME: ${{ secrets.AZURE_TRUSTED_SIGNING_ACCOUNT_NAME }}
          # AZURE_CERTIFICATE_PROFILE_NAME: ${{ secrets.AZURE_CERTIFICATE_PROFILE_NAME }}

        with:
          projectPath: rel/app
          args: --target ${{ matrix.gui_target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: voyager-${{ matrix.gui_target }}
          path: rel/app/src-tauri/target/${{ matrix.gui_target }}/release/bundle/
          if-no-files-found: error